// <auto-generated />
namespace Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class alter_paymentdetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_paymentdetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201803251451283_alter_paymentdetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
