// <auto-generated />
namespace Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addTypecolumn_invoice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTypecolumn_invoice));
        
        string IMigrationMetadata.Id
        {
            get { return "201803291322286_addTypecolumn_invoice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
