// <auto-generated />
namespace Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _Alter_paymentdetail_deleteOrderId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_Alter_paymentdetail_deleteOrderId));
        
        string IMigrationMetadata.Id
        {
            get { return "201803251532444__Alter_paymentdetail_deleteOrderId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
